# Deploy Nuxt (static) to GitHub Pages — project page compatible
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Prefer clean, reproducible installs
      - run: npm ci

      # IMPORTANT: set base URL for project pages (replace <repo>)
      # If you're using a custom domain or a user page, omit the env var.
      - run: NUXT_APP_BASE_URL=/<repo>/ npx nuxt build --preset github_pages

      # Ensure Jekyll is bypassed so _nuxt/ is served
      - run: touch .output/public/.nojekyll

      # (Optional) keep a custom domain working if you have one
      - name: Preserve CNAME if present
        run: |
          if [ -f CNAME ]; then cp CNAME .output/public/CNAME; fi
          if [ -f public/CNAME ]; then cp public/CNAME .output/public/CNAME; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
